### ISSUE TITLE
Help Wanted: How to use k8s operator with external db/s3

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3927]
Mattermost user `joram` from https://community-daily.mattermost.com has requested the following be documented:

```
Got it. We do need better docs around using external mysql/s3 but it's very possible and actually what I'd suggest as the preferred way to use the operator. Here's an example of a manifest using external mysql/s3:

```yaml
apiVersion: mattermost.com/v1alpha1
kind: ClusterInstallation
metadata:
  namespace: mynamespace
spec:
  database:
    secret: dbsecret
  ingressAnnotations:
    kubernetes.io/ingress.class: nginx-controller
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/server-snippets: gzip on;
  ingressName: somesite.com
  mattermostEnv:
  - name: MM_PLUGINSETTINGS_ENABLEUPLOADS
    value: "false"
  - name: MM_FILESETTINGS_AMAZONS3SSE
    value: "true"
  mattermostLicenseSecret: licensesecret
  minio:
    externalBucket: somebucket
    externalURL: s3.amazonaws.com
    secret: s3secret

----

apiVersion: v1
kind: Secret
type: Opaque
data:
  accesskey: somebase64accesskey
  secretkey: somebase64secretkey
metadata:
  name: s3secret
  namespace: mynamespace

----

apiVersion: v1
kind: Secret
type: Opaque
data:
  DB_CONNECTION_STRING: somebase64encodedsqlconnectionstring
metadata:
  name: dbsecret
  namespace: mynamespace
```

For custom CAs I think we'd need some extra support for that if you didn't want to rebuild the images with it baked in
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/jrnkrrje37r49fd8nokw8qa7ua).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._
